PubgArena/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.RegisterView.as_view(), name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('blog.urls')),
    path('mapsNguns/', include('mapsNguns.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path

from .views import (PostListView,
                    PostDetailView,
                    PostCreateView,
                    PostUpdateView,
                    PostDeleteView,
                    UserPostListView,
                    about)

urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('about/', about, name='blog-about'),
    path('post/add/', PostCreateView.as_view(), name='blog-add'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='blog-detail'),
    path('post/<int:pk>/edit/', PostUpdateView.as_view(), name='blog-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='blog-delete'),
    path('user/<str:username>/', UserPostListView.as_view(), name='user-post'),

]

mapsNguns/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('maps/', MapListView.as_view(), name='list-map'),
    path('city/', CityListView.as_view(), name='list-city'),
    path('maps/<int:pk>/city/', CityListView.as_view(), name='list-map-city'),
    path('weapons/', WeaponListView.as_view(), name='list-weapon'),
    path('weapons/<int:pk>/', WeaponDetailView.as_view(), name='detail-weapon'),
    path('weapons/<int:pk>/', WeaponDetailView.as_view(), name='detail-weapon'),
    path('weapons/<int:pk>/maps/', MapWeaponListView.as_view(), name='detail-weapon-map'),
    path('weapons/demo/', WeaponView.as_view(), name='demo-ajax-view'),

]

mapsNguns/models.py
from django.db import models
from django.utils.text import gettext_lazy as _

from PIL import Image

GENRE_CHOICES = (
    ("am", "AMBUSH"),
    ("sn", "SNIPING"),
    ("as", "ASSAULT"),
    ("st", "STEALTH"),
)

WEAPON_TYPE = (
    ("smg", "Sub Machine Gun"),
    ("rifle", "Rifle"),
    ("handgun", "Hand Gun"),
    ("melee", "Melee"),
    ("sniper", "sniper")
)

BULLET_TYPE = (
    ("5.56", "5.56mm"),
    ("9", "9mm"),
    ("7.82", "7.82mm"),
    ("12", "12mm"),
)

MODE_TYPE = (
    ("3", "ABS"),
    ("2", "AB/BS/AS"),
    ("1", "S")
)


class Map(models.Model):
    name = models.CharField(max_length=255, verbose_name=_("Map Name"))
    genre = models.CharField(max_length=255, choices=GENRE_CHOICES, blank=True)
    short_desc = models.TextField(verbose_name=_("Short Description"))
    long_desc = models.TextField(verbose_name=_("Long Description"))

    def __str__(self):
        return self.name

    def city_count(self):
        return str(self.city_set.all().count())

    class Meta:
        verbose_name_plural = _("Maps")


class Weapon(models.Model):
    maps = models.ManyToManyField(to=Map)
    name = models.CharField(max_length=255, verbose_name=_("Weapon Name"))
    type = models.CharField(max_length=255, choices=WEAPON_TYPE, default="melee")
    bullet = models.CharField(max_length=255, choices=BULLET_TYPE, blank=True)
    slots = models.PositiveIntegerField(verbose_name=_("No. of custom slots"))
    modes = models.CharField(max_length=255, choices=MODE_TYPE, blank=True)
    desc = models.TextField(verbose_name=_("Weapon Description"))
    damage = models.PositiveIntegerField(verbose_name=_("Damage level out of 5"))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = _("Weapons")


class Vehicle(models.Model):
    maps = models.ManyToManyField(to=Map)
    name = models.CharField(max_length=255, verbose_name=_("Vehicle Name"))
    is_drivable = models.BooleanField(verbose_name=_("Is Drivable"), default=True)
    capacity = models.PositiveIntegerField(verbose_name=_("No. of seats"))
    desc = models.TextField(verbose_name=_("Description"))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = _("Vehicles")


class City(models.Model):
    map = models.ForeignKey(to=Map, on_delete=models.PROTECT)
    name = models.CharField(max_length=255, verbose_name=_("City Name"))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = _("Cities")


class MapImage(models.Model):
    map = models.ForeignKey(to=Map, on_delete=models.PROTECT)
    image = models.ImageField(upload_to="map_pics", verbose_name=_("Images"))

    def __str__(self):
        return self.map.name + "'s" + "Image"

    class Meta:
        verbose_name_plural = _("Map Images")

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        super(MapImage, self).save()
        image = Image.open(self.image.path)
        if image.height > 300 and image.width > 300:
            output_size = (300, 300)
            image.thumbnail(output_size)
            image.save(self.image.path)


class WeaponImage(models.Model):
    weapon = models.ForeignKey(to=Weapon, on_delete=models.PROTECT)
    image = models.ImageField(upload_to="gun_pics", verbose_name=_("Images"))

    def __str__(self):
        return self.weapon.name + "'s" + "Image"

    class Meta:
        verbose_name_plural = _("Weapon Images")

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        super(WeaponImage, self).save()
        image = Image.open(self.image.path)
        if image.height > 300 and image.width > 300:
            output_size = (300, 300)
            image.thumbnail(output_size)
            image.save(self.image.path)

mapsNguns/views.py
from django.views import generic

from .models import Map, City, Vehicle, Weapon


class MapListView(generic.ListView):
    queryset = Map.objects.all()
    template_name = "mapsNguns/list-map.html"


class MapWeaponListView(generic.ListView):
    queryset = Map.objects.all()
    template_name = "mapsNguns/list-map.html"

    def get_queryset(self):
        qs = super(MapWeaponListView, self).get_queryset()
        weapon = Weapon.objects.get(pk=self.kwargs.get('pk'))
        if weapon:
            return qs.filter(weapon=weapon)
        return qs


class CityListView(generic.ListView):
    queryset = City.objects.all()
    template_name = "mapsNguns/list-city.html"

    def get_queryset(self):
        qs = super(CityListView, self).get_queryset()
        map = Map.objects.get(pk=self.kwargs.get('pk'))
        if map:
            return qs.filter(map=map)
        return qs


class VehicleListView(generic.ListView):
    queryset = Vehicle.objects.all()
    template_name = "mapsNguns/list-vehicle.html"


class WeaponListView(generic.ListView):
    queryset = Weapon.objects.all()
    template_name = "mapsNguns/list-weapon.html"


class WeaponDetailView(generic.DetailView):
    queryset = Weapon.objects.all()
    template_name = "mapsNguns/detail-weapons.html"
    context_object_name = "weapon"


class WeaponView(generic.TemplateView):
    template_name = "mapsNguns/demo.html"

mapsNguns/templates/mapsNguns/demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>AJAX demo</title>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>
<body id=”theBody”>

<div id="main"><h3>JQuery Event Handlers</h3></div>

<div>

    <img src=’http://www.newthinktank.com/favicon.png’ id=’logo’ alt=’Little Brain’/>

</div>

<br/>

<div>

    <p><strong>Events Triggered on the Page:</strong></p>

    <p id=”second”>Waiting for Event</p>

    <p id=”third”>Waiting for Change</p>

</div>


<div>

    <p><strong>Key Events Triggered on the Page:</strong></p>

    <span id=”fourth”>Key Pressed:</span>

    <span id=”fifth”>Waiting for Change</span>

</div>
<br/>


<div>

    <p><strong>Mouse Movements on the Page:</strong></p>

    <span id=”sixth”>Mouse X Coordinate:</span>

    <span id=”seventh”>Waiting for Change</span><br/>

    <span id=”eighth”>Mouse Y Coordinate:</span>

    <span id=”ninth”>Waiting for Change</span><br/>

    <span>Textbox Changed: </span>

    <span id=”tenth”>Waiting for Event</span><br/>

    <span>Element Changed When: </span>

    <span id=”eleventh”>Event Occurred When</span>

</div>
<br/>

<form>

    <button type=”button” id=”oneButton”>Alert on Click</button>

    <button type=”button” id=”twoButton”>Click on me Twice</button>

    <button type=”button” id=”threeButton”>Unbind the Logo</button>

    <input type=’text’ id=”textBox1″ size=40>

    <input type=’submit’ value=’Send’>

</form>

<script type="text/javascript">

    $(document).ready(function () {

        $("#oneButton").on("click", function () {
            console.log("i am here!");
            alert("Alert button is clicked");
        })

        $("#tenth").css("color", "red");

    });

    function alertButtonClick() {
        alert("Alert button is clicked.");
    }

</script>

</body>
</html>

mapsNguns/templates/mapsNguns/detail-weapons.html
{% extends "blog/base.html" %}
{% block content %}
    <h2 class="article-title">{{ weapon.name }}</h2>
    <br>
    <article class="media content-section">

        {% for img in weapon.weaponimage_set.all %}
            <img src="{{ img.image.url }}">
        {% endfor %}

        <h5>Weapon type: </h5><br>{{ weapon.type }}
        <br>
        <h5>Weapon Bullet: </h5>{{ weapon.bullet }}
        <br>
        <h5>Weapon Slots: </h5>{{ weapon.slots }}
        <br>
        <h5>Weapon Modes: </h5>{{ weapon.modes }}
        <br>
        <h5>Weapon Damage /5: </h5>{{ weapon.damage }}
        <br>
        {{ weapon.desc }}
{% endblock content %}

mapsNguns/templates/mapsNguns/list-city.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>City</title>
</head>
<body>

<table>

    {% for obj in object_list %}
        <tr>
            <td>{{ obj.name }}</td>
            <td>{{ obj.map.name }}</td>
        </tr>
    {% endfor %}
</table>
</body>
</html>

mapsNguns/templates/mapsNguns/list-map.html
{% extends "blog/base.html" %}
{% block content %}
    <table>
        <th>MAP NAME</th>
        <th>MAP IMAGES</th>
        <th>GENRE</th>
        <th>SHORT DESC</th>
        <th>LONG DESC</th>
        <th>CITIES</th>
        {% for obj in object_list %}
            <tr>
                <td><h1>{{ obj.name }}</h1></td>

                <td>{% for img in obj.mapimage_set.all %}
                    <img class="rounded-circle account-img" src="{{ img.image.url }}">
                {% endfor %}</td>

                <td>{{ obj.genre }}</td>
                <td>{{ obj.short_desc }}</td>
                <td>{{ obj.long_desc }}</td>
                <td><a href="{% url 'list-map-city' obj.id %}">{{ obj.city_count }}</a></td>
            </tr>
        {% endfor %}

    </table>
{% endblock content %}

mapsNguns/templates/mapsNguns/list-vehicle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Vehicle</title>
</head>
<body>

</body>
</html>

mapsNguns/templates/mapsNguns/list-weapon.html
{% extends "blog/base.html" %}
{% block content %}


    <article class="media content-section">
        <div class="media-body">
            {% for obj in object_list %}
                {% for img in obj.weaponimage_set.all %}
                    <img class="rounded-circle article-img" src="{{ img.image.url }}">
                {% endfor %}
                <a href="{% url 'detail-weapon' obj.id %}">{{ obj.name }}</a>
                <p class="article-content">{{ obj.desc }}</p>
            {% endfor %}
        </div>
    </article>

{% endblock content %}